// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Scene.proto

#ifndef PROTOBUF_Scene_2eproto__INCLUDED
#define PROTOBUF_Scene_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace killer {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Scene_2eproto();
void protobuf_AssignDesc_Scene_2eproto();
void protobuf_ShutdownFile_Scene_2eproto();

class Vector3;
class Vector4;
class U3DPhysxScene;
class U3DPhysxSphere;
class U3DPhysxBox;
class U3DPhysxCapsule;
class U3DPhysxMesh;

enum ColliderType {
  BOX = 1,
  SPHERE = 2,
  CAPSULE = 3,
  MESH = 4
};
bool ColliderType_IsValid(int value);
const ColliderType ColliderType_MIN = BOX;
const ColliderType ColliderType_MAX = MESH;
const int ColliderType_ARRAYSIZE = ColliderType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ColliderType_descriptor();
inline const ::std::string& ColliderType_Name(ColliderType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ColliderType_descriptor(), value);
}
inline bool ColliderType_Parse(
    const ::std::string& name, ColliderType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ColliderType>(
    ColliderType_descriptor(), name, value);
}
// ===================================================================

class Vector3 : public ::google::protobuf::Message {
 public:
  Vector3();
  virtual ~Vector3();

  Vector3(const Vector3& from);

  inline Vector3& operator=(const Vector3& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector3& default_instance();

  void Swap(Vector3* other);

  // implements Message ----------------------------------------------

  Vector3* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Vector3& from);
  void MergeFrom(const Vector3& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1 [default = 0];
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline double x() const;
  inline void set_x(double value);

  // optional double y = 2 [default = 0];
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline double y() const;
  inline void set_y(double value);

  // optional double z = 3 [default = 0];
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline double z() const;
  inline void set_z(double value);

  // @@protoc_insertion_point(class_scope:killer.proto.Vector3)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  friend void  protobuf_AddDesc_Scene_2eproto();
  friend void protobuf_AssignDesc_Scene_2eproto();
  friend void protobuf_ShutdownFile_Scene_2eproto();

  void InitAsDefaultInstance();
  static Vector3* default_instance_;
};
// -------------------------------------------------------------------

class Vector4 : public ::google::protobuf::Message {
 public:
  Vector4();
  virtual ~Vector4();

  Vector4(const Vector4& from);

  inline Vector4& operator=(const Vector4& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector4& default_instance();

  void Swap(Vector4* other);

  // implements Message ----------------------------------------------

  Vector4* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Vector4& from);
  void MergeFrom(const Vector4& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1 [default = 0];
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline double x() const;
  inline void set_x(double value);

  // optional double y = 2 [default = 0];
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline double y() const;
  inline void set_y(double value);

  // optional double z = 3 [default = 0];
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline double z() const;
  inline void set_z(double value);

  // optional double w = 4 [default = 0];
  inline bool has_w() const;
  inline void clear_w();
  static const int kWFieldNumber = 4;
  inline double w() const;
  inline void set_w(double value);

  // @@protoc_insertion_point(class_scope:killer.proto.Vector4)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  inline void set_has_w();
  inline void clear_has_w();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  double w_;
  friend void  protobuf_AddDesc_Scene_2eproto();
  friend void protobuf_AssignDesc_Scene_2eproto();
  friend void protobuf_ShutdownFile_Scene_2eproto();

  void InitAsDefaultInstance();
  static Vector4* default_instance_;
};
// -------------------------------------------------------------------

class U3DPhysxScene : public ::google::protobuf::Message {
 public:
  U3DPhysxScene();
  virtual ~U3DPhysxScene();

  U3DPhysxScene(const U3DPhysxScene& from);

  inline U3DPhysxScene& operator=(const U3DPhysxScene& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const U3DPhysxScene& default_instance();

  void Swap(U3DPhysxScene* other);

  // implements Message ----------------------------------------------

  U3DPhysxScene* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const U3DPhysxScene& from);
  void MergeFrom(const U3DPhysxScene& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional string scene_name = 2;
  inline bool has_scene_name() const;
  inline void clear_scene_name();
  static const int kSceneNameFieldNumber = 2;
  inline const ::std::string& scene_name() const;
  inline void set_scene_name(const ::std::string& value);
  inline void set_scene_name(const char* value);
  inline void set_scene_name(const char* value, size_t size);
  inline ::std::string* mutable_scene_name();
  inline ::std::string* release_scene_name();
  inline void set_allocated_scene_name(::std::string* scene_name);

  // repeated .killer.proto.U3DPhysxBox box_collider = 3;
  inline int box_collider_size() const;
  inline void clear_box_collider();
  static const int kBoxColliderFieldNumber = 3;
  inline const ::killer::proto::U3DPhysxBox& box_collider(int index) const;
  inline ::killer::proto::U3DPhysxBox* mutable_box_collider(int index);
  inline ::killer::proto::U3DPhysxBox* add_box_collider();
  inline const ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxBox >&
      box_collider() const;
  inline ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxBox >*
      mutable_box_collider();

  // repeated .killer.proto.U3DPhysxSphere sphere_collider = 4;
  inline int sphere_collider_size() const;
  inline void clear_sphere_collider();
  static const int kSphereColliderFieldNumber = 4;
  inline const ::killer::proto::U3DPhysxSphere& sphere_collider(int index) const;
  inline ::killer::proto::U3DPhysxSphere* mutable_sphere_collider(int index);
  inline ::killer::proto::U3DPhysxSphere* add_sphere_collider();
  inline const ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxSphere >&
      sphere_collider() const;
  inline ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxSphere >*
      mutable_sphere_collider();

  // repeated .killer.proto.U3DPhysxCapsule capsule_collider = 5;
  inline int capsule_collider_size() const;
  inline void clear_capsule_collider();
  static const int kCapsuleColliderFieldNumber = 5;
  inline const ::killer::proto::U3DPhysxCapsule& capsule_collider(int index) const;
  inline ::killer::proto::U3DPhysxCapsule* mutable_capsule_collider(int index);
  inline ::killer::proto::U3DPhysxCapsule* add_capsule_collider();
  inline const ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxCapsule >&
      capsule_collider() const;
  inline ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxCapsule >*
      mutable_capsule_collider();

  // repeated .killer.proto.U3DPhysxMesh mesh_collider = 6;
  inline int mesh_collider_size() const;
  inline void clear_mesh_collider();
  static const int kMeshColliderFieldNumber = 6;
  inline const ::killer::proto::U3DPhysxMesh& mesh_collider(int index) const;
  inline ::killer::proto::U3DPhysxMesh* mutable_mesh_collider(int index);
  inline ::killer::proto::U3DPhysxMesh* add_mesh_collider();
  inline const ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxMesh >&
      mesh_collider() const;
  inline ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxMesh >*
      mutable_mesh_collider();

  // @@protoc_insertion_point(class_scope:killer.proto.U3DPhysxScene)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_scene_name();
  inline void clear_has_scene_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* scene_name_;
  ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxBox > box_collider_;
  ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxSphere > sphere_collider_;
  ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxCapsule > capsule_collider_;
  ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxMesh > mesh_collider_;
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_Scene_2eproto();
  friend void protobuf_AssignDesc_Scene_2eproto();
  friend void protobuf_ShutdownFile_Scene_2eproto();

  void InitAsDefaultInstance();
  static U3DPhysxScene* default_instance_;
};
// -------------------------------------------------------------------

class U3DPhysxSphere : public ::google::protobuf::Message {
 public:
  U3DPhysxSphere();
  virtual ~U3DPhysxSphere();

  U3DPhysxSphere(const U3DPhysxSphere& from);

  inline U3DPhysxSphere& operator=(const U3DPhysxSphere& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const U3DPhysxSphere& default_instance();

  void Swap(U3DPhysxSphere* other);

  // implements Message ----------------------------------------------

  U3DPhysxSphere* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const U3DPhysxSphere& from);
  void MergeFrom(const U3DPhysxSphere& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional .killer.proto.ColliderType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::killer::proto::ColliderType type() const;
  inline void set_type(::killer::proto::ColliderType value);

  // optional .killer.proto.Vector3 pos = 3;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 3;
  inline const ::killer::proto::Vector3& pos() const;
  inline ::killer::proto::Vector3* mutable_pos();
  inline ::killer::proto::Vector3* release_pos();
  inline void set_allocated_pos(::killer::proto::Vector3* pos);

  // optional double radius = 4;
  inline bool has_radius() const;
  inline void clear_radius();
  static const int kRadiusFieldNumber = 4;
  inline double radius() const;
  inline void set_radius(double value);

  // optional .killer.proto.Vector4 rotation = 5;
  inline bool has_rotation() const;
  inline void clear_rotation();
  static const int kRotationFieldNumber = 5;
  inline const ::killer::proto::Vector4& rotation() const;
  inline ::killer::proto::Vector4* mutable_rotation();
  inline ::killer::proto::Vector4* release_rotation();
  inline void set_allocated_rotation(::killer::proto::Vector4* rotation);

  // @@protoc_insertion_point(class_scope:killer.proto.U3DPhysxSphere)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_pos();
  inline void clear_has_pos();
  inline void set_has_radius();
  inline void clear_has_radius();
  inline void set_has_rotation();
  inline void clear_has_rotation();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  int type_;
  ::killer::proto::Vector3* pos_;
  double radius_;
  ::killer::proto::Vector4* rotation_;
  friend void  protobuf_AddDesc_Scene_2eproto();
  friend void protobuf_AssignDesc_Scene_2eproto();
  friend void protobuf_ShutdownFile_Scene_2eproto();

  void InitAsDefaultInstance();
  static U3DPhysxSphere* default_instance_;
};
// -------------------------------------------------------------------

class U3DPhysxBox : public ::google::protobuf::Message {
 public:
  U3DPhysxBox();
  virtual ~U3DPhysxBox();

  U3DPhysxBox(const U3DPhysxBox& from);

  inline U3DPhysxBox& operator=(const U3DPhysxBox& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const U3DPhysxBox& default_instance();

  void Swap(U3DPhysxBox* other);

  // implements Message ----------------------------------------------

  U3DPhysxBox* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const U3DPhysxBox& from);
  void MergeFrom(const U3DPhysxBox& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional .killer.proto.ColliderType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::killer::proto::ColliderType type() const;
  inline void set_type(::killer::proto::ColliderType value);

  // optional .killer.proto.Vector3 pos = 3;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 3;
  inline const ::killer::proto::Vector3& pos() const;
  inline ::killer::proto::Vector3* mutable_pos();
  inline ::killer::proto::Vector3* release_pos();
  inline void set_allocated_pos(::killer::proto::Vector3* pos);

  // optional double x_extents = 4;
  inline bool has_x_extents() const;
  inline void clear_x_extents();
  static const int kXExtentsFieldNumber = 4;
  inline double x_extents() const;
  inline void set_x_extents(double value);

  // optional double y_extents = 5;
  inline bool has_y_extents() const;
  inline void clear_y_extents();
  static const int kYExtentsFieldNumber = 5;
  inline double y_extents() const;
  inline void set_y_extents(double value);

  // optional double z_extents = 6;
  inline bool has_z_extents() const;
  inline void clear_z_extents();
  static const int kZExtentsFieldNumber = 6;
  inline double z_extents() const;
  inline void set_z_extents(double value);

  // optional .killer.proto.Vector4 rotation = 7;
  inline bool has_rotation() const;
  inline void clear_rotation();
  static const int kRotationFieldNumber = 7;
  inline const ::killer::proto::Vector4& rotation() const;
  inline ::killer::proto::Vector4* mutable_rotation();
  inline ::killer::proto::Vector4* release_rotation();
  inline void set_allocated_rotation(::killer::proto::Vector4* rotation);

  // @@protoc_insertion_point(class_scope:killer.proto.U3DPhysxBox)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_pos();
  inline void clear_has_pos();
  inline void set_has_x_extents();
  inline void clear_has_x_extents();
  inline void set_has_y_extents();
  inline void clear_has_y_extents();
  inline void set_has_z_extents();
  inline void clear_has_z_extents();
  inline void set_has_rotation();
  inline void clear_has_rotation();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  int type_;
  ::killer::proto::Vector3* pos_;
  double x_extents_;
  double y_extents_;
  double z_extents_;
  ::killer::proto::Vector4* rotation_;
  friend void  protobuf_AddDesc_Scene_2eproto();
  friend void protobuf_AssignDesc_Scene_2eproto();
  friend void protobuf_ShutdownFile_Scene_2eproto();

  void InitAsDefaultInstance();
  static U3DPhysxBox* default_instance_;
};
// -------------------------------------------------------------------

class U3DPhysxCapsule : public ::google::protobuf::Message {
 public:
  U3DPhysxCapsule();
  virtual ~U3DPhysxCapsule();

  U3DPhysxCapsule(const U3DPhysxCapsule& from);

  inline U3DPhysxCapsule& operator=(const U3DPhysxCapsule& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const U3DPhysxCapsule& default_instance();

  void Swap(U3DPhysxCapsule* other);

  // implements Message ----------------------------------------------

  U3DPhysxCapsule* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const U3DPhysxCapsule& from);
  void MergeFrom(const U3DPhysxCapsule& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional .killer.proto.ColliderType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::killer::proto::ColliderType type() const;
  inline void set_type(::killer::proto::ColliderType value);

  // optional .killer.proto.Vector3 pos = 3;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 3;
  inline const ::killer::proto::Vector3& pos() const;
  inline ::killer::proto::Vector3* mutable_pos();
  inline ::killer::proto::Vector3* release_pos();
  inline void set_allocated_pos(::killer::proto::Vector3* pos);

  // optional double raduis = 4;
  inline bool has_raduis() const;
  inline void clear_raduis();
  static const int kRaduisFieldNumber = 4;
  inline double raduis() const;
  inline void set_raduis(double value);

  // optional double height = 5;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 5;
  inline double height() const;
  inline void set_height(double value);

  // optional .killer.proto.Vector4 rotation = 6;
  inline bool has_rotation() const;
  inline void clear_rotation();
  static const int kRotationFieldNumber = 6;
  inline const ::killer::proto::Vector4& rotation() const;
  inline ::killer::proto::Vector4* mutable_rotation();
  inline ::killer::proto::Vector4* release_rotation();
  inline void set_allocated_rotation(::killer::proto::Vector4* rotation);

  // @@protoc_insertion_point(class_scope:killer.proto.U3DPhysxCapsule)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_pos();
  inline void clear_has_pos();
  inline void set_has_raduis();
  inline void clear_has_raduis();
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_rotation();
  inline void clear_has_rotation();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  int type_;
  ::killer::proto::Vector3* pos_;
  double raduis_;
  double height_;
  ::killer::proto::Vector4* rotation_;
  friend void  protobuf_AddDesc_Scene_2eproto();
  friend void protobuf_AssignDesc_Scene_2eproto();
  friend void protobuf_ShutdownFile_Scene_2eproto();

  void InitAsDefaultInstance();
  static U3DPhysxCapsule* default_instance_;
};
// -------------------------------------------------------------------

class U3DPhysxMesh : public ::google::protobuf::Message {
 public:
  U3DPhysxMesh();
  virtual ~U3DPhysxMesh();

  U3DPhysxMesh(const U3DPhysxMesh& from);

  inline U3DPhysxMesh& operator=(const U3DPhysxMesh& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const U3DPhysxMesh& default_instance();

  void Swap(U3DPhysxMesh* other);

  // implements Message ----------------------------------------------

  U3DPhysxMesh* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const U3DPhysxMesh& from);
  void MergeFrom(const U3DPhysxMesh& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional .killer.proto.ColliderType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::killer::proto::ColliderType type() const;
  inline void set_type(::killer::proto::ColliderType value);

  // optional int32 vertex_count = 3;
  inline bool has_vertex_count() const;
  inline void clear_vertex_count();
  static const int kVertexCountFieldNumber = 3;
  inline ::google::protobuf::int32 vertex_count() const;
  inline void set_vertex_count(::google::protobuf::int32 value);

  // repeated .killer.proto.Vector3 vertices = 4;
  inline int vertices_size() const;
  inline void clear_vertices();
  static const int kVerticesFieldNumber = 4;
  inline const ::killer::proto::Vector3& vertices(int index) const;
  inline ::killer::proto::Vector3* mutable_vertices(int index);
  inline ::killer::proto::Vector3* add_vertices();
  inline const ::google::protobuf::RepeatedPtrField< ::killer::proto::Vector3 >&
      vertices() const;
  inline ::google::protobuf::RepeatedPtrField< ::killer::proto::Vector3 >*
      mutable_vertices();

  // optional .killer.proto.Vector4 rotation = 5;
  inline bool has_rotation() const;
  inline void clear_rotation();
  static const int kRotationFieldNumber = 5;
  inline const ::killer::proto::Vector4& rotation() const;
  inline ::killer::proto::Vector4* mutable_rotation();
  inline ::killer::proto::Vector4* release_rotation();
  inline void set_allocated_rotation(::killer::proto::Vector4* rotation);

  // @@protoc_insertion_point(class_scope:killer.proto.U3DPhysxMesh)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_vertex_count();
  inline void clear_has_vertex_count();
  inline void set_has_rotation();
  inline void clear_has_rotation();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  int type_;
  ::google::protobuf::RepeatedPtrField< ::killer::proto::Vector3 > vertices_;
  ::killer::proto::Vector4* rotation_;
  ::google::protobuf::int32 vertex_count_;
  friend void  protobuf_AddDesc_Scene_2eproto();
  friend void protobuf_AssignDesc_Scene_2eproto();
  friend void protobuf_ShutdownFile_Scene_2eproto();

  void InitAsDefaultInstance();
  static U3DPhysxMesh* default_instance_;
};
// ===================================================================


// ===================================================================

// Vector3

// optional double x = 1 [default = 0];
inline bool Vector3::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector3::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector3::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector3::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Vector3::x() const {
  // @@protoc_insertion_point(field_get:killer.proto.Vector3.x)
  return x_;
}
inline void Vector3::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.Vector3.x)
}

// optional double y = 2 [default = 0];
inline bool Vector3::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector3::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector3::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector3::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Vector3::y() const {
  // @@protoc_insertion_point(field_get:killer.proto.Vector3.y)
  return y_;
}
inline void Vector3::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.Vector3.y)
}

// optional double z = 3 [default = 0];
inline bool Vector3::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Vector3::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Vector3::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Vector3::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Vector3::z() const {
  // @@protoc_insertion_point(field_get:killer.proto.Vector3.z)
  return z_;
}
inline void Vector3::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.Vector3.z)
}

// -------------------------------------------------------------------

// Vector4

// optional double x = 1 [default = 0];
inline bool Vector4::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector4::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector4::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector4::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Vector4::x() const {
  // @@protoc_insertion_point(field_get:killer.proto.Vector4.x)
  return x_;
}
inline void Vector4::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.Vector4.x)
}

// optional double y = 2 [default = 0];
inline bool Vector4::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector4::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector4::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector4::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Vector4::y() const {
  // @@protoc_insertion_point(field_get:killer.proto.Vector4.y)
  return y_;
}
inline void Vector4::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.Vector4.y)
}

// optional double z = 3 [default = 0];
inline bool Vector4::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Vector4::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Vector4::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Vector4::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Vector4::z() const {
  // @@protoc_insertion_point(field_get:killer.proto.Vector4.z)
  return z_;
}
inline void Vector4::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.Vector4.z)
}

// optional double w = 4 [default = 0];
inline bool Vector4::has_w() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Vector4::set_has_w() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Vector4::clear_has_w() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Vector4::clear_w() {
  w_ = 0;
  clear_has_w();
}
inline double Vector4::w() const {
  // @@protoc_insertion_point(field_get:killer.proto.Vector4.w)
  return w_;
}
inline void Vector4::set_w(double value) {
  set_has_w();
  w_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.Vector4.w)
}

// -------------------------------------------------------------------

// U3DPhysxScene

// optional int32 id = 1;
inline bool U3DPhysxScene::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void U3DPhysxScene::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void U3DPhysxScene::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void U3DPhysxScene::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 U3DPhysxScene::id() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxScene.id)
  return id_;
}
inline void U3DPhysxScene::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxScene.id)
}

// optional string scene_name = 2;
inline bool U3DPhysxScene::has_scene_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void U3DPhysxScene::set_has_scene_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void U3DPhysxScene::clear_has_scene_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void U3DPhysxScene::clear_scene_name() {
  if (scene_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    scene_name_->clear();
  }
  clear_has_scene_name();
}
inline const ::std::string& U3DPhysxScene::scene_name() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxScene.scene_name)
  return *scene_name_;
}
inline void U3DPhysxScene::set_scene_name(const ::std::string& value) {
  set_has_scene_name();
  if (scene_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    scene_name_ = new ::std::string;
  }
  scene_name_->assign(value);
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxScene.scene_name)
}
inline void U3DPhysxScene::set_scene_name(const char* value) {
  set_has_scene_name();
  if (scene_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    scene_name_ = new ::std::string;
  }
  scene_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:killer.proto.U3DPhysxScene.scene_name)
}
inline void U3DPhysxScene::set_scene_name(const char* value, size_t size) {
  set_has_scene_name();
  if (scene_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    scene_name_ = new ::std::string;
  }
  scene_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:killer.proto.U3DPhysxScene.scene_name)
}
inline ::std::string* U3DPhysxScene::mutable_scene_name() {
  set_has_scene_name();
  if (scene_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    scene_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxScene.scene_name)
  return scene_name_;
}
inline ::std::string* U3DPhysxScene::release_scene_name() {
  clear_has_scene_name();
  if (scene_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = scene_name_;
    scene_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void U3DPhysxScene::set_allocated_scene_name(::std::string* scene_name) {
  if (scene_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete scene_name_;
  }
  if (scene_name) {
    set_has_scene_name();
    scene_name_ = scene_name;
  } else {
    clear_has_scene_name();
    scene_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:killer.proto.U3DPhysxScene.scene_name)
}

// repeated .killer.proto.U3DPhysxBox box_collider = 3;
inline int U3DPhysxScene::box_collider_size() const {
  return box_collider_.size();
}
inline void U3DPhysxScene::clear_box_collider() {
  box_collider_.Clear();
}
inline const ::killer::proto::U3DPhysxBox& U3DPhysxScene::box_collider(int index) const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxScene.box_collider)
  return box_collider_.Get(index);
}
inline ::killer::proto::U3DPhysxBox* U3DPhysxScene::mutable_box_collider(int index) {
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxScene.box_collider)
  return box_collider_.Mutable(index);
}
inline ::killer::proto::U3DPhysxBox* U3DPhysxScene::add_box_collider() {
  // @@protoc_insertion_point(field_add:killer.proto.U3DPhysxScene.box_collider)
  return box_collider_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxBox >&
U3DPhysxScene::box_collider() const {
  // @@protoc_insertion_point(field_list:killer.proto.U3DPhysxScene.box_collider)
  return box_collider_;
}
inline ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxBox >*
U3DPhysxScene::mutable_box_collider() {
  // @@protoc_insertion_point(field_mutable_list:killer.proto.U3DPhysxScene.box_collider)
  return &box_collider_;
}

// repeated .killer.proto.U3DPhysxSphere sphere_collider = 4;
inline int U3DPhysxScene::sphere_collider_size() const {
  return sphere_collider_.size();
}
inline void U3DPhysxScene::clear_sphere_collider() {
  sphere_collider_.Clear();
}
inline const ::killer::proto::U3DPhysxSphere& U3DPhysxScene::sphere_collider(int index) const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxScene.sphere_collider)
  return sphere_collider_.Get(index);
}
inline ::killer::proto::U3DPhysxSphere* U3DPhysxScene::mutable_sphere_collider(int index) {
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxScene.sphere_collider)
  return sphere_collider_.Mutable(index);
}
inline ::killer::proto::U3DPhysxSphere* U3DPhysxScene::add_sphere_collider() {
  // @@protoc_insertion_point(field_add:killer.proto.U3DPhysxScene.sphere_collider)
  return sphere_collider_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxSphere >&
U3DPhysxScene::sphere_collider() const {
  // @@protoc_insertion_point(field_list:killer.proto.U3DPhysxScene.sphere_collider)
  return sphere_collider_;
}
inline ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxSphere >*
U3DPhysxScene::mutable_sphere_collider() {
  // @@protoc_insertion_point(field_mutable_list:killer.proto.U3DPhysxScene.sphere_collider)
  return &sphere_collider_;
}

// repeated .killer.proto.U3DPhysxCapsule capsule_collider = 5;
inline int U3DPhysxScene::capsule_collider_size() const {
  return capsule_collider_.size();
}
inline void U3DPhysxScene::clear_capsule_collider() {
  capsule_collider_.Clear();
}
inline const ::killer::proto::U3DPhysxCapsule& U3DPhysxScene::capsule_collider(int index) const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxScene.capsule_collider)
  return capsule_collider_.Get(index);
}
inline ::killer::proto::U3DPhysxCapsule* U3DPhysxScene::mutable_capsule_collider(int index) {
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxScene.capsule_collider)
  return capsule_collider_.Mutable(index);
}
inline ::killer::proto::U3DPhysxCapsule* U3DPhysxScene::add_capsule_collider() {
  // @@protoc_insertion_point(field_add:killer.proto.U3DPhysxScene.capsule_collider)
  return capsule_collider_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxCapsule >&
U3DPhysxScene::capsule_collider() const {
  // @@protoc_insertion_point(field_list:killer.proto.U3DPhysxScene.capsule_collider)
  return capsule_collider_;
}
inline ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxCapsule >*
U3DPhysxScene::mutable_capsule_collider() {
  // @@protoc_insertion_point(field_mutable_list:killer.proto.U3DPhysxScene.capsule_collider)
  return &capsule_collider_;
}

// repeated .killer.proto.U3DPhysxMesh mesh_collider = 6;
inline int U3DPhysxScene::mesh_collider_size() const {
  return mesh_collider_.size();
}
inline void U3DPhysxScene::clear_mesh_collider() {
  mesh_collider_.Clear();
}
inline const ::killer::proto::U3DPhysxMesh& U3DPhysxScene::mesh_collider(int index) const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxScene.mesh_collider)
  return mesh_collider_.Get(index);
}
inline ::killer::proto::U3DPhysxMesh* U3DPhysxScene::mutable_mesh_collider(int index) {
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxScene.mesh_collider)
  return mesh_collider_.Mutable(index);
}
inline ::killer::proto::U3DPhysxMesh* U3DPhysxScene::add_mesh_collider() {
  // @@protoc_insertion_point(field_add:killer.proto.U3DPhysxScene.mesh_collider)
  return mesh_collider_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxMesh >&
U3DPhysxScene::mesh_collider() const {
  // @@protoc_insertion_point(field_list:killer.proto.U3DPhysxScene.mesh_collider)
  return mesh_collider_;
}
inline ::google::protobuf::RepeatedPtrField< ::killer::proto::U3DPhysxMesh >*
U3DPhysxScene::mutable_mesh_collider() {
  // @@protoc_insertion_point(field_mutable_list:killer.proto.U3DPhysxScene.mesh_collider)
  return &mesh_collider_;
}

// -------------------------------------------------------------------

// U3DPhysxSphere

// optional int32 id = 1;
inline bool U3DPhysxSphere::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void U3DPhysxSphere::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void U3DPhysxSphere::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void U3DPhysxSphere::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 U3DPhysxSphere::id() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxSphere.id)
  return id_;
}
inline void U3DPhysxSphere::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxSphere.id)
}

// optional .killer.proto.ColliderType type = 2;
inline bool U3DPhysxSphere::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void U3DPhysxSphere::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void U3DPhysxSphere::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void U3DPhysxSphere::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::killer::proto::ColliderType U3DPhysxSphere::type() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxSphere.type)
  return static_cast< ::killer::proto::ColliderType >(type_);
}
inline void U3DPhysxSphere::set_type(::killer::proto::ColliderType value) {
  assert(::killer::proto::ColliderType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxSphere.type)
}

// optional .killer.proto.Vector3 pos = 3;
inline bool U3DPhysxSphere::has_pos() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void U3DPhysxSphere::set_has_pos() {
  _has_bits_[0] |= 0x00000004u;
}
inline void U3DPhysxSphere::clear_has_pos() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void U3DPhysxSphere::clear_pos() {
  if (pos_ != NULL) pos_->::killer::proto::Vector3::Clear();
  clear_has_pos();
}
inline const ::killer::proto::Vector3& U3DPhysxSphere::pos() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxSphere.pos)
  return pos_ != NULL ? *pos_ : *default_instance_->pos_;
}
inline ::killer::proto::Vector3* U3DPhysxSphere::mutable_pos() {
  set_has_pos();
  if (pos_ == NULL) pos_ = new ::killer::proto::Vector3;
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxSphere.pos)
  return pos_;
}
inline ::killer::proto::Vector3* U3DPhysxSphere::release_pos() {
  clear_has_pos();
  ::killer::proto::Vector3* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void U3DPhysxSphere::set_allocated_pos(::killer::proto::Vector3* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    set_has_pos();
  } else {
    clear_has_pos();
  }
  // @@protoc_insertion_point(field_set_allocated:killer.proto.U3DPhysxSphere.pos)
}

// optional double radius = 4;
inline bool U3DPhysxSphere::has_radius() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void U3DPhysxSphere::set_has_radius() {
  _has_bits_[0] |= 0x00000008u;
}
inline void U3DPhysxSphere::clear_has_radius() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void U3DPhysxSphere::clear_radius() {
  radius_ = 0;
  clear_has_radius();
}
inline double U3DPhysxSphere::radius() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxSphere.radius)
  return radius_;
}
inline void U3DPhysxSphere::set_radius(double value) {
  set_has_radius();
  radius_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxSphere.radius)
}

// optional .killer.proto.Vector4 rotation = 5;
inline bool U3DPhysxSphere::has_rotation() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void U3DPhysxSphere::set_has_rotation() {
  _has_bits_[0] |= 0x00000010u;
}
inline void U3DPhysxSphere::clear_has_rotation() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void U3DPhysxSphere::clear_rotation() {
  if (rotation_ != NULL) rotation_->::killer::proto::Vector4::Clear();
  clear_has_rotation();
}
inline const ::killer::proto::Vector4& U3DPhysxSphere::rotation() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxSphere.rotation)
  return rotation_ != NULL ? *rotation_ : *default_instance_->rotation_;
}
inline ::killer::proto::Vector4* U3DPhysxSphere::mutable_rotation() {
  set_has_rotation();
  if (rotation_ == NULL) rotation_ = new ::killer::proto::Vector4;
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxSphere.rotation)
  return rotation_;
}
inline ::killer::proto::Vector4* U3DPhysxSphere::release_rotation() {
  clear_has_rotation();
  ::killer::proto::Vector4* temp = rotation_;
  rotation_ = NULL;
  return temp;
}
inline void U3DPhysxSphere::set_allocated_rotation(::killer::proto::Vector4* rotation) {
  delete rotation_;
  rotation_ = rotation;
  if (rotation) {
    set_has_rotation();
  } else {
    clear_has_rotation();
  }
  // @@protoc_insertion_point(field_set_allocated:killer.proto.U3DPhysxSphere.rotation)
}

// -------------------------------------------------------------------

// U3DPhysxBox

// optional int32 id = 1;
inline bool U3DPhysxBox::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void U3DPhysxBox::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void U3DPhysxBox::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void U3DPhysxBox::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 U3DPhysxBox::id() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxBox.id)
  return id_;
}
inline void U3DPhysxBox::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxBox.id)
}

// optional .killer.proto.ColliderType type = 2;
inline bool U3DPhysxBox::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void U3DPhysxBox::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void U3DPhysxBox::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void U3DPhysxBox::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::killer::proto::ColliderType U3DPhysxBox::type() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxBox.type)
  return static_cast< ::killer::proto::ColliderType >(type_);
}
inline void U3DPhysxBox::set_type(::killer::proto::ColliderType value) {
  assert(::killer::proto::ColliderType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxBox.type)
}

// optional .killer.proto.Vector3 pos = 3;
inline bool U3DPhysxBox::has_pos() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void U3DPhysxBox::set_has_pos() {
  _has_bits_[0] |= 0x00000004u;
}
inline void U3DPhysxBox::clear_has_pos() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void U3DPhysxBox::clear_pos() {
  if (pos_ != NULL) pos_->::killer::proto::Vector3::Clear();
  clear_has_pos();
}
inline const ::killer::proto::Vector3& U3DPhysxBox::pos() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxBox.pos)
  return pos_ != NULL ? *pos_ : *default_instance_->pos_;
}
inline ::killer::proto::Vector3* U3DPhysxBox::mutable_pos() {
  set_has_pos();
  if (pos_ == NULL) pos_ = new ::killer::proto::Vector3;
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxBox.pos)
  return pos_;
}
inline ::killer::proto::Vector3* U3DPhysxBox::release_pos() {
  clear_has_pos();
  ::killer::proto::Vector3* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void U3DPhysxBox::set_allocated_pos(::killer::proto::Vector3* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    set_has_pos();
  } else {
    clear_has_pos();
  }
  // @@protoc_insertion_point(field_set_allocated:killer.proto.U3DPhysxBox.pos)
}

// optional double x_extents = 4;
inline bool U3DPhysxBox::has_x_extents() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void U3DPhysxBox::set_has_x_extents() {
  _has_bits_[0] |= 0x00000008u;
}
inline void U3DPhysxBox::clear_has_x_extents() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void U3DPhysxBox::clear_x_extents() {
  x_extents_ = 0;
  clear_has_x_extents();
}
inline double U3DPhysxBox::x_extents() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxBox.x_extents)
  return x_extents_;
}
inline void U3DPhysxBox::set_x_extents(double value) {
  set_has_x_extents();
  x_extents_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxBox.x_extents)
}

// optional double y_extents = 5;
inline bool U3DPhysxBox::has_y_extents() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void U3DPhysxBox::set_has_y_extents() {
  _has_bits_[0] |= 0x00000010u;
}
inline void U3DPhysxBox::clear_has_y_extents() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void U3DPhysxBox::clear_y_extents() {
  y_extents_ = 0;
  clear_has_y_extents();
}
inline double U3DPhysxBox::y_extents() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxBox.y_extents)
  return y_extents_;
}
inline void U3DPhysxBox::set_y_extents(double value) {
  set_has_y_extents();
  y_extents_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxBox.y_extents)
}

// optional double z_extents = 6;
inline bool U3DPhysxBox::has_z_extents() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void U3DPhysxBox::set_has_z_extents() {
  _has_bits_[0] |= 0x00000020u;
}
inline void U3DPhysxBox::clear_has_z_extents() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void U3DPhysxBox::clear_z_extents() {
  z_extents_ = 0;
  clear_has_z_extents();
}
inline double U3DPhysxBox::z_extents() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxBox.z_extents)
  return z_extents_;
}
inline void U3DPhysxBox::set_z_extents(double value) {
  set_has_z_extents();
  z_extents_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxBox.z_extents)
}

// optional .killer.proto.Vector4 rotation = 7;
inline bool U3DPhysxBox::has_rotation() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void U3DPhysxBox::set_has_rotation() {
  _has_bits_[0] |= 0x00000040u;
}
inline void U3DPhysxBox::clear_has_rotation() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void U3DPhysxBox::clear_rotation() {
  if (rotation_ != NULL) rotation_->::killer::proto::Vector4::Clear();
  clear_has_rotation();
}
inline const ::killer::proto::Vector4& U3DPhysxBox::rotation() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxBox.rotation)
  return rotation_ != NULL ? *rotation_ : *default_instance_->rotation_;
}
inline ::killer::proto::Vector4* U3DPhysxBox::mutable_rotation() {
  set_has_rotation();
  if (rotation_ == NULL) rotation_ = new ::killer::proto::Vector4;
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxBox.rotation)
  return rotation_;
}
inline ::killer::proto::Vector4* U3DPhysxBox::release_rotation() {
  clear_has_rotation();
  ::killer::proto::Vector4* temp = rotation_;
  rotation_ = NULL;
  return temp;
}
inline void U3DPhysxBox::set_allocated_rotation(::killer::proto::Vector4* rotation) {
  delete rotation_;
  rotation_ = rotation;
  if (rotation) {
    set_has_rotation();
  } else {
    clear_has_rotation();
  }
  // @@protoc_insertion_point(field_set_allocated:killer.proto.U3DPhysxBox.rotation)
}

// -------------------------------------------------------------------

// U3DPhysxCapsule

// optional int32 id = 1;
inline bool U3DPhysxCapsule::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void U3DPhysxCapsule::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void U3DPhysxCapsule::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void U3DPhysxCapsule::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 U3DPhysxCapsule::id() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxCapsule.id)
  return id_;
}
inline void U3DPhysxCapsule::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxCapsule.id)
}

// optional .killer.proto.ColliderType type = 2;
inline bool U3DPhysxCapsule::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void U3DPhysxCapsule::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void U3DPhysxCapsule::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void U3DPhysxCapsule::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::killer::proto::ColliderType U3DPhysxCapsule::type() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxCapsule.type)
  return static_cast< ::killer::proto::ColliderType >(type_);
}
inline void U3DPhysxCapsule::set_type(::killer::proto::ColliderType value) {
  assert(::killer::proto::ColliderType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxCapsule.type)
}

// optional .killer.proto.Vector3 pos = 3;
inline bool U3DPhysxCapsule::has_pos() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void U3DPhysxCapsule::set_has_pos() {
  _has_bits_[0] |= 0x00000004u;
}
inline void U3DPhysxCapsule::clear_has_pos() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void U3DPhysxCapsule::clear_pos() {
  if (pos_ != NULL) pos_->::killer::proto::Vector3::Clear();
  clear_has_pos();
}
inline const ::killer::proto::Vector3& U3DPhysxCapsule::pos() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxCapsule.pos)
  return pos_ != NULL ? *pos_ : *default_instance_->pos_;
}
inline ::killer::proto::Vector3* U3DPhysxCapsule::mutable_pos() {
  set_has_pos();
  if (pos_ == NULL) pos_ = new ::killer::proto::Vector3;
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxCapsule.pos)
  return pos_;
}
inline ::killer::proto::Vector3* U3DPhysxCapsule::release_pos() {
  clear_has_pos();
  ::killer::proto::Vector3* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void U3DPhysxCapsule::set_allocated_pos(::killer::proto::Vector3* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    set_has_pos();
  } else {
    clear_has_pos();
  }
  // @@protoc_insertion_point(field_set_allocated:killer.proto.U3DPhysxCapsule.pos)
}

// optional double raduis = 4;
inline bool U3DPhysxCapsule::has_raduis() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void U3DPhysxCapsule::set_has_raduis() {
  _has_bits_[0] |= 0x00000008u;
}
inline void U3DPhysxCapsule::clear_has_raduis() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void U3DPhysxCapsule::clear_raduis() {
  raduis_ = 0;
  clear_has_raduis();
}
inline double U3DPhysxCapsule::raduis() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxCapsule.raduis)
  return raduis_;
}
inline void U3DPhysxCapsule::set_raduis(double value) {
  set_has_raduis();
  raduis_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxCapsule.raduis)
}

// optional double height = 5;
inline bool U3DPhysxCapsule::has_height() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void U3DPhysxCapsule::set_has_height() {
  _has_bits_[0] |= 0x00000010u;
}
inline void U3DPhysxCapsule::clear_has_height() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void U3DPhysxCapsule::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline double U3DPhysxCapsule::height() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxCapsule.height)
  return height_;
}
inline void U3DPhysxCapsule::set_height(double value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxCapsule.height)
}

// optional .killer.proto.Vector4 rotation = 6;
inline bool U3DPhysxCapsule::has_rotation() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void U3DPhysxCapsule::set_has_rotation() {
  _has_bits_[0] |= 0x00000020u;
}
inline void U3DPhysxCapsule::clear_has_rotation() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void U3DPhysxCapsule::clear_rotation() {
  if (rotation_ != NULL) rotation_->::killer::proto::Vector4::Clear();
  clear_has_rotation();
}
inline const ::killer::proto::Vector4& U3DPhysxCapsule::rotation() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxCapsule.rotation)
  return rotation_ != NULL ? *rotation_ : *default_instance_->rotation_;
}
inline ::killer::proto::Vector4* U3DPhysxCapsule::mutable_rotation() {
  set_has_rotation();
  if (rotation_ == NULL) rotation_ = new ::killer::proto::Vector4;
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxCapsule.rotation)
  return rotation_;
}
inline ::killer::proto::Vector4* U3DPhysxCapsule::release_rotation() {
  clear_has_rotation();
  ::killer::proto::Vector4* temp = rotation_;
  rotation_ = NULL;
  return temp;
}
inline void U3DPhysxCapsule::set_allocated_rotation(::killer::proto::Vector4* rotation) {
  delete rotation_;
  rotation_ = rotation;
  if (rotation) {
    set_has_rotation();
  } else {
    clear_has_rotation();
  }
  // @@protoc_insertion_point(field_set_allocated:killer.proto.U3DPhysxCapsule.rotation)
}

// -------------------------------------------------------------------

// U3DPhysxMesh

// optional int32 id = 1;
inline bool U3DPhysxMesh::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void U3DPhysxMesh::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void U3DPhysxMesh::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void U3DPhysxMesh::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 U3DPhysxMesh::id() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxMesh.id)
  return id_;
}
inline void U3DPhysxMesh::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxMesh.id)
}

// optional .killer.proto.ColliderType type = 2;
inline bool U3DPhysxMesh::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void U3DPhysxMesh::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void U3DPhysxMesh::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void U3DPhysxMesh::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::killer::proto::ColliderType U3DPhysxMesh::type() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxMesh.type)
  return static_cast< ::killer::proto::ColliderType >(type_);
}
inline void U3DPhysxMesh::set_type(::killer::proto::ColliderType value) {
  assert(::killer::proto::ColliderType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxMesh.type)
}

// optional int32 vertex_count = 3;
inline bool U3DPhysxMesh::has_vertex_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void U3DPhysxMesh::set_has_vertex_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void U3DPhysxMesh::clear_has_vertex_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void U3DPhysxMesh::clear_vertex_count() {
  vertex_count_ = 0;
  clear_has_vertex_count();
}
inline ::google::protobuf::int32 U3DPhysxMesh::vertex_count() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxMesh.vertex_count)
  return vertex_count_;
}
inline void U3DPhysxMesh::set_vertex_count(::google::protobuf::int32 value) {
  set_has_vertex_count();
  vertex_count_ = value;
  // @@protoc_insertion_point(field_set:killer.proto.U3DPhysxMesh.vertex_count)
}

// repeated .killer.proto.Vector3 vertices = 4;
inline int U3DPhysxMesh::vertices_size() const {
  return vertices_.size();
}
inline void U3DPhysxMesh::clear_vertices() {
  vertices_.Clear();
}
inline const ::killer::proto::Vector3& U3DPhysxMesh::vertices(int index) const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxMesh.vertices)
  return vertices_.Get(index);
}
inline ::killer::proto::Vector3* U3DPhysxMesh::mutable_vertices(int index) {
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxMesh.vertices)
  return vertices_.Mutable(index);
}
inline ::killer::proto::Vector3* U3DPhysxMesh::add_vertices() {
  // @@protoc_insertion_point(field_add:killer.proto.U3DPhysxMesh.vertices)
  return vertices_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::killer::proto::Vector3 >&
U3DPhysxMesh::vertices() const {
  // @@protoc_insertion_point(field_list:killer.proto.U3DPhysxMesh.vertices)
  return vertices_;
}
inline ::google::protobuf::RepeatedPtrField< ::killer::proto::Vector3 >*
U3DPhysxMesh::mutable_vertices() {
  // @@protoc_insertion_point(field_mutable_list:killer.proto.U3DPhysxMesh.vertices)
  return &vertices_;
}

// optional .killer.proto.Vector4 rotation = 5;
inline bool U3DPhysxMesh::has_rotation() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void U3DPhysxMesh::set_has_rotation() {
  _has_bits_[0] |= 0x00000010u;
}
inline void U3DPhysxMesh::clear_has_rotation() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void U3DPhysxMesh::clear_rotation() {
  if (rotation_ != NULL) rotation_->::killer::proto::Vector4::Clear();
  clear_has_rotation();
}
inline const ::killer::proto::Vector4& U3DPhysxMesh::rotation() const {
  // @@protoc_insertion_point(field_get:killer.proto.U3DPhysxMesh.rotation)
  return rotation_ != NULL ? *rotation_ : *default_instance_->rotation_;
}
inline ::killer::proto::Vector4* U3DPhysxMesh::mutable_rotation() {
  set_has_rotation();
  if (rotation_ == NULL) rotation_ = new ::killer::proto::Vector4;
  // @@protoc_insertion_point(field_mutable:killer.proto.U3DPhysxMesh.rotation)
  return rotation_;
}
inline ::killer::proto::Vector4* U3DPhysxMesh::release_rotation() {
  clear_has_rotation();
  ::killer::proto::Vector4* temp = rotation_;
  rotation_ = NULL;
  return temp;
}
inline void U3DPhysxMesh::set_allocated_rotation(::killer::proto::Vector4* rotation) {
  delete rotation_;
  rotation_ = rotation;
  if (rotation) {
    set_has_rotation();
  } else {
    clear_has_rotation();
  }
  // @@protoc_insertion_point(field_set_allocated:killer.proto.U3DPhysxMesh.rotation)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace killer

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::killer::proto::ColliderType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::killer::proto::ColliderType>() {
  return ::killer::proto::ColliderType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Scene_2eproto__INCLUDED
